/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sdhashsrv_constants.h"

namespace sdhash {

const sdhashsrvConstants g_sdhashsrv_constants;

sdhashsrvConstants::sdhashsrvConstants() {
}

} // namespace

