/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sdhashsrv_CONSTANTS_H
#define sdhashsrv_CONSTANTS_H

#include "sdhashsrv_types.h"

namespace sdhash {

class sdhashsrvConstants {
 public:
  sdhashsrvConstants();

};

extern const sdhashsrvConstants g_sdhashsrv_constants;

} // namespace

#endif
